kind: ConfigMap
apiVersion: v1
metadata:
  name: module-serverless
data:
  module-serverless.json: |
    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Application",
      "metadata": {
        "name": "{{ .Values.module.module_serverless.name }}",
        "namespace": "{{ .Values.module.module_serverless.namespace }}",
        "finalizers": [
          "resources-finalizer.argocd.argoproj.io/foreground"
        ]
      },
      "spec": {
        "ignoreDifferences": [
          {
            "group": "serving.knative.dev",
            "kind": "Service",
            "jsonPointers": [
              "/spec/template/spec/containers/0/name",
              "/spec/template/spec/containers/0/env"
            ]
          }
        ],
        "destination": {
          "name": "",
          "namespace": "{{ .Values.module.module_serverless.destination.namespace }}",
          "server": "https://kubernetes.default.svc"
        },
        "project": "default",
        "syncPolicy": {
          "automated": {
            "prune": false,
            "selfHeal": false
          }
        },
        "source": {
          "repoURL": "{{ .Values.module.module_serverless.source.repoUrl }}",
          "targetRevision": "{{ .Values.module.module_serverless.source.targetRevision }}",
          "path": "{{ .Values.module.module_serverless.source.path }}",
          "helm": {
            "values": ""
          }
        }
      }
    }